### PR TITLE
Crop cleanup and automation streamlining.

### PR DESCRIPTION
**Pull request by C0bra5**
The changes in this PR should help with the EIG rewrite I'm working on and harvest automation in general.

I left out some of the work I want to do for now since I feel the need to ask questions first:

Some things do for loops for random durations, but those random calls are in the check part of the for loops. This usually results in a much lower average drop value. If this lower drop average is intentional, Wouldn't it be preferable to roll once and use a smaller value that would preserve the existing rates?

Examples:
- https://github.com/GTNewHorizons/ThaumicBases/blob/d73d5c7821862d5f9c447d688cedd1d13ca07ab6/src/main/java/tb/common/block/BlockRainbowCactus.java#L46 ~2.2 extra rounds in average
- https://github.com/GTNewHorizons/ThaumicBases/blob/d73d5c7821862d5f9c447d688cedd1d13ca07ab6/src/main/java/tb/common/block/BlockAshroom.java#L45 ~5.7 extra rounds in an average
- https://github.com/GTNewHorizons/ThaumicBases/blob/d73d5c7821862d5f9c447d688cedd1d13ca07ab6/src/main/java/tb/common/block/BlockTBPlant.java#L163 ~0.5, ~0.8 and ~1.2 extra rounds depending on the fortune level

This formula approximates the average number of extra rounds. it's not perfect but it's close enough: $x=\sqrt{\frac{\phi}{4}}y^{2}+\phi y+1$ where
- $\phi$ is the golden ratio ~1.618
- $x$ is the max value of the random call
- $y$ is the average extra rounds

I noticed that many getDrops methods only need the world for calls to RNG. Decoupling the world would be a "nice to have" for my EIG rewrite. I'm down to decouple it where possible and standardize the process.

By default, the rainbow cactus is supposed to generate green dye more frequently, but when Gregtech is installed, it drops all dyes in equal amounts. Is this an oversight, or is this intended?

### CODE REVIEW

**Comment by Alastors** [comment]
I mean I'm personally fine with this, but we need more devs to rule on this one since it's a balance change, even if this might be a bug

**Comment by C0bra5** [comment]
I forgot to ask about the rainbow cactus dye drop rates. By default, the rainbow cactus is supposed to generate green dye more frequently, but when Gregtech is installed, it drops all dyes in equal amounts. Is this an oversight, or is this intended?

**Comment by Alastors** [comment]
No idea actually, never used the cactus outside of the pack so 🤷🏻‍♀️

**Comment by C0bra5** [comment]
The commit for those lines links to this issue: [#12543](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12543).

It mentions "replacing" the missing dyes, so it could be intended that it doesn't drop more green dye. I just want to clear out the potential uncertainty and potentially add a note denoting the fact that the change is intended so no one else gets confused about it.

**Review by OneEyeMaker — CHANGES_REQUESTED** [review]
1) Please define count of iterations before the loops. As for amount of *random* iterations, one should be lowered *at least little bit* to prevent major buff.
2) It's intended behavior for rainbow cactus to drop green dye more often than other dyes. Original idea was simple: to drop every *vanilla* dye in equal proportion and replace otherwise useful ones (lapis/bone meal) with green dye.

**Comment by C0bra5** [comment]
> 1. Please define count of iterations before the loops. As for amount of _random_ iterations, one should be lowered _at least little bit_ to prevent major buff.
Alright, I'll use the numbers denoted by that function in the top post since they should retain the original drop rates.

>     2. It's intended behavior for rainbow cactus to drop green dye more often than other dyes. Original idea was simple: to drop every _vanilla_ dye in equal proportion and replace otherwise useful ones (lapis/bone meal) with green dye.
I'm confused. Do you want me to make green more prominent again while keeping the fact that it drops every dye?

**Comment by Alastors** [comment]
> 2) It's intended behavior for rainbow cactus to drop green dye more often than other dyes. Original idea was simple: to drop every *vanilla* dye in equal proportion and replace otherwise useful ones (lapis/bone meal) with green dye.

Going to point out on this one, why would we care if lapis or bonemeal is useful as a dye? We have active duplication recipes for both as well as crops, this is just another option so I'd reject this request for change frankly. This is a nothing burger

**Comment by OneEyeMaker** [comment]
Second paragraph in my post was *explanation* and not a request. Original authors of this mod balanced it this way. And this piece of code was not removed to prevent making GT a *hard dependency*.

@C0bra5 Cleanup loops and I can approve this PR.

**Comment by Alastors** [comment]
It's a balance PR so we need admin approval

**Comment by Dream-Master** [comment]
if this is approved by a dev i can do an admin approve as well

**Comment by C0bra5** [comment]
I took the liberty of removing the mention that the cacti drop more green dye and that it doesn't drop certain dyes if the Gregtech is installed.

As for the random calls, every crop change should be able to match the old drop rates. the bonuses from the random calls could be evaluated as https://oeis.org/A000435 divided by https://oeis.org/A000169 multiplied by 2

Primal shrooms were just a case of finding the 32nd term of the sequence
https://github.com/C0bra5/ThaumicBases/blob/b25705ec609ca491035d3209680593e599f973ff/src/main/java/tb/common/block/BlockAshroom.java#L47-L49

Same with rainbow cacti, it's just the 8th term of the sequence
https://github.com/C0bra5/ThaumicBases/blob/b25705ec609ca491035d3209680593e599f973ff/src/main/java/tb/common/block/BlockRainbowCactus.java#L59-L61

Sweed was just a case of moving the random call a bit
https://github.com/C0bra5/ThaumicBases/blob/b25705ec609ca491035d3209680593e599f973ff/src/main/java/tb/common/block/BlockSweed.java#L55-L56

BlockTBPlant was the one that led me to find the formula to calculate the average number of rounds you used to be able to get in average. There isn't an efficient way to calculate it without relying on math that has to rely on big integers, so I left it as an approximation of the old rates and capped the max drop count to 3. Having a fortune level higher than three will just give you a higher chance of getting three rounds at once. However, I could have been more accurate with the growth rate of the fortune bonus.
https://github.com/C0bra5/ThaumicBases/blob/b25705ec609ca491035d3209680593e599f973ff/src/main/java/tb/common/block/BlockTBPlant.java#L163-L177

**Review by OneEyeMaker — APPROVED** [review]
Nice job!
And there's no need to be *so* precise - just don't make *major* buff 😄

**Pull request merged**
