### PR TITLE
Fix Ancient Blocks being Invalid Stabilisers

### PR DESCRIPTION
**Pull request by 54M44R**
Closes GTNewHorizons/GT-New-Horizons-Modpack/issues/15540

### CODE REVIEW

**Review by OneEyeMaker — APPROVED** [review]

**Comment by Dream-Master** [comment]
It’s a fix not need to freeze

**Comment by Dream-Master** [comment]
Ok let me check

**Comment by Dream-Master** [comment]
i send the dev a pm to fix the other pr and we are good i hope

**Comment by 54M44R** [comment]
> its not a fix. Its changing a cosmetic block to be a stabilizer. More importantly though: it is 2 PRs, you cant only merge one.

The original Thaumic Bases code does show they were not intended to be stabilizers, though common knowledge is that they are due to wikis stating they should be (along with the tooltip issue)

This was done more so for existing consistency as in commit d74f599 from /pull/17 has introduced additional stabilizers due to the method `canStabaliseInfusion()` being hardcoded to return `true`. The two options would be to either:
- Revert these changes which would cause players using stabilizers such as Ancient Cobblestone to be invalid
- Allow all decorative blocks to be used as stabilizers

I chose the latter due to Ancient Cobblestone being very cheap already. Since the alternatives are far more expensive, it would only benefit players who preferred the visuals of the ancient blocks

Whether this choice was objectively correct or not I'm not sure. I am more than happy to write another PR to revert these changes along with /pull/17. What are your thoughts @Dream-Master @chochem ?

**Comment by Alastors** [comment]
Respectfully, infusion stabilizers are effectively free, partly because of GTNH's cross mod compat.

Another example besides ancient cobble would be salis mundis blocks, salis mundis of course can be duplicated and turned into blocks for free through the use of a rosa mysteria farm

**Comment by chochem** [comment]
I don't particularly care either way as long as they are not cheaper than ancient cobblestone. (e.g. no chisel please)

And on the history: ancient Cobblestone was not a stabilizer for most of the 10 year history of GTNH either. After it was made a stabilizer (I think thats the PR you linked), we then adjusted the recipe slightly. Actually that was me I think. And yes, the current very cheap ancient cobble recipe is the 'nerfed' version. :P

**Comment by chochem** [comment]
dream just wants you to resolve the review in the other PR so that he can merge that as well

**Pull request merged**
